
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { ConnectButton } from '@rainbow-me/rainbowkit';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Crypto Chess</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Crypto Chess

        </h1>

        <p className={styles.description}>
          Chess.com tournaments with Crypto prizes
        </p>
        <a href="tournaments/new"><button>New Tournament Contract</button></a>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made by Falco90 during Flare x Encode April 2025
        </a>
      </footer>
    </div>
  );
};

export default Home;
