import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import Header from "../../components/Header";
import { useState } from "react";
import DeployContract from "../../hooks/use-deploy-contract";
import { Box, TextField, Button, List, Collapse, ListItemButton, ListItemIcon, ListItemText, ListSubheader, ListItem } from "@mui/material";

const New = () => {
    const [tournamentData, setTournamentData] = useState({
        name: "",
        url: "",
        organizer: "",
        status: "",
        fee: "",
        maxPlayers: 0
    });
    const [fetchedTournament, setFetchedTournament] = useState(false);

    async function fetchTournament(event: any) {
        event.preventDefault();

        await fetch(tournamentData.url, {
            method: 'GET',
            mode: 'cors',
        }).then(async (response) => {
            const data = await response.json();
            setTournamentData({
                ...tournamentData,
                name: data.name,
                organizer: data.organizer,
                status: data.status
            })

            setFetchedTournament(true);
        });

    }

    return (
        <div className={styles.container} >
            <Header />
            <Head>
                <title>Crypto Chess</title>
                <meta
                    content="Generated by @rainbow-me/create-rainbowkit"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>

            <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>

                <h1>
                    Deploy New Tournament
                </h1>
                <Box>
                    <TextField id="outlined-basic" label="Chess.com URL" variant="outlined" value={tournamentData.url} onChange={(e) => {
                        setTournamentData({ ...tournamentData, url: e.target.value })
                    }} />
                    <Button onClick={(e) => fetchTournament(e)} type="submit">Link</Button>
                </Box>
                {fetchedTournament ?
                    <Box>
                        <Box>
                            <Box>
                                <TextField id="outlined-basic" label="Players" variant="outlined" type="number" value={tournamentData.maxPlayers} onChange={(e) => {
                                    setTournamentData({ ...tournamentData, maxPlayers: parseInt(e.target.value) })
                                }} />
                            </Box>
                            <Box>
                                <TextField id="outlined-basic" label="Fee (ether)" variant="outlined" type="number" value={tournamentData.fee} onChange={(e) => {
                                    setTournamentData({ ...tournamentData, fee: e.target.value })
                                }} />
                            </Box>
                        </Box>
                        <List
                            sx={{ width: '100%', maxWidth: 360, bgcolor: 'background.paper' }}
                            component="nav"
                            aria-labelledby="nested-list-subheader"
                            subheader={
                                <ListSubheader component="div" id="nested-list-subheader">
                                    Tournament Details
                                </ListSubheader>
                            }
                        >
                            <ListItem>
                                <ListItemText primary={`URL: ${tournamentData.url}`} />
                            </ListItem>
                            <ListItem>
                                <ListItemText primary={`Status: ${tournamentData.status}`} />
                            </ListItem>
                            <ListItem>
                                <ListItemText primary={`Max Amount of Players: ${tournamentData.maxPlayers}`} />
                            </ListItem>
                            <ListItem>
                                <ListItemText primary="Current Amount of Players:" />
                            </ListItem>
                        </List>
                        <DeployContract url={tournamentData.url} maxPlayers={tournamentData.maxPlayers} fee={tournamentData.fee} />
                    </Box> : ""}
            </Box>

            <footer className={styles.footer}>
                <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
                    Made by Falco90 during Flare x Encode April 2025
                </a>
            </footer>
        </div >
    )
}

export default New;