import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useState } from "react";
import DeployContract from "../../hooks/use-deploy-contract";

const New = () => {
    const [tournamentData, setTournamentData] = useState({
        name: "",
        url: "",
        organizer: "",
        status: ""
    });
    async function fetchTournament() {
        const data = await fetch("https://api.chess.com/pub/tournament/-33rd-chesscom-quick-knockouts-1401-1600", {
            method: 'GET', // or 'POST'
            mode: 'cors', // This tells the browser it's a CORS request
        }).then(async (response) => {
            const data = await response.json();
            setTournamentData({
                name: data.name,
                url: data.url,
                organizer: data.organizer,
                status: data.status
            })
        });

    }

    async function deployContract() {

    }
    return (
        <div className={styles.container} >
            <Head>
                <title>Crypto Chess</title>
                <meta
                    content="Generated by @rainbow-me/create-rainbowkit"
                    name="description"
                />
                <link href="/favicon.ico" rel="icon" />
            </Head>

            <main className={styles.main}>
                <ConnectButton />

                <h1 className={styles.title}>
                    Deploy New Tournament
                </h1>
                <form action={fetchTournament}>
                    <input type="text" />
                    <label htmlFor="">Chess.com tournament URL</label>
                    <button type="submit">Link</button>
                </form>
                < div >
                    <div>name: {tournamentData ? tournamentData.name : ""}</div>
                    <div>url: {tournamentData ? tournamentData.url : ""}</div>
                    <div>organizer: {tournamentData ? tournamentData.organizer : ""}</div>
                    <div>status: {tournamentData ? tournamentData.status : ""}</div>
                </div>
                <DeployContract />
            </main >

            <footer className={styles.footer}>
                <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
                    Made by Falco90 during Flare x Encode April 2025
                </a>
            </footer>
        </div >
    )
}

export default New;